//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetGenius.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetGenius.Resources.Views.Home.Index.ru", typeof(Index_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бесполезная хрень.
        /// </summary>
        internal static string _10_Best_Rated_Webflow_Live_Chat_Plugins {
            get {
                return ResourceManager.GetString("10 Best Rated Webflow Live Chat Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Социал медиа аккаунт.
        /// </summary>
        internal static string _3_Social_Media_Account {
            get {
                return ResourceManager.GetString("3 Social Media Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хрень как и utility pages.
        /// </summary>
        internal static string _8_Best_Webflow_Quiz_Plugins_For_Your_Website {
            get {
                return ResourceManager.GetString("8 Best Webflow Quiz Plugins For Your Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Пер Монтх.
        /// </summary>
        internal static string _Per_Month {
            get {
                return ResourceManager.GetString("/Per Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пер Еар.
        /// </summary>
        internal static string _Per_Year {
            get {
                return ResourceManager.GetString("/Per Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Демонстрация почестей, наград и отраслевого признания, полученных нашей компанией.
        /// </summary>
        internal static string A_Showcase_of_Honors__Accolades__and_Industry_Recognition_Earned_by_Our_Company {
            get {
                return ResourceManager.GetString("A Showcase of Honors, Accolades, and Industry Recognition Earned by Our Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Более умная, быстрая и безопасная сеть.
        /// </summary>
        internal static string A_Smarter__Faster__and_More_Secure_Network_Experience {
            get {
                return ResourceManager.GetString("A Smarter, Faster, and More Secure Network Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О нас.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расширенная фильтрация.
        /// </summary>
        internal static string Advanced_Filtering {
            get {
                return ResourceManager.GetString("Advanced Filtering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расширенная система выставления счетов.
        /// </summary>
        internal static string Advanced_Invoice_System {
            get {
                return ResourceManager.GetString("Advanced Invoice System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Алл Феатуре.
        /// </summary>
        internal static string All_Feature {
            get {
                return ResourceManager.GetString("All Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аппс.
        /// </summary>
        internal static string Apps {
            get {
                return ResourceManager.GetString("Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средняя рентабельность инвестиций.
        /// </summary>
        internal static string Average_ROI {
            get {
                return ResourceManager.GetString("Average ROI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Худшая цена.
        /// </summary>
        internal static string Best_Price {
            get {
                return ResourceManager.GetString("Best Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Награда за лучшее программное обеспечение.
        /// </summary>
        internal static string Best_Software_Award {
            get {
                return ResourceManager.GetString("Best Software Award", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блог.
        /// </summary>
        internal static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Боарды.
        /// </summary>
        internal static string Boards {
            get {
                return ResourceManager.GetString("Boards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ждем.
        /// </summary>
        internal static string Coming_Soon {
            get {
                return ResourceManager.GetString("Coming Soon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус компаний.
        /// </summary>
        internal static string Company_Status {
            get {
                return ResourceManager.GetString("Company Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подвердждение емайл.
        /// </summary>
        internal static string Confirm_email {
            get {
                return ResourceManager.GetString("Confirm email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контак контак.
        /// </summary>
        internal static string Contact_and_company {
            get {
                return ResourceManager.GetString("Contact and company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мощная функция CRM.
        /// </summary>
        internal static string CRM_Power_Feature {
            get {
                return ResourceManager.GetString("CRM Power Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребительская ценность.
        /// </summary>
        internal static string Customer_Value {
            get {
                return ResourceManager.GetString("Customer Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Панель.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблица данных – (Расширенный фильтр).
        /// </summary>
        internal static string Data_table____Advance_filter_ {
            get {
                return ResourceManager.GetString("Data table - (Advance filter)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Погрузитесь в инновационные решения и услуги, переопределяющие отраслевые стандарты..
        /// </summary>
        internal static string Delve_Into_the_Innovative_Solutions_and_Services_Redefining_Industry_Standards_ {
            get {
                return ResourceManager.GetString("Delve Into the Innovative Solutions and Services Redefining Industry Standards.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откройте для себя идеальный план, соответствующий вашему бюджету, и раскройте весь потенциал наших решений.
        /// </summary>
        internal static string Discover_the_Perfect_Plan_to_Fit_Your_Budget_and_Unleash_the_Full_Potential_of_Our_Solutions {
            get {
                return ResourceManager.GetString("Discover the Perfect Plan to Fit Your Budget and Unleash the Full Potential of Ou" +
                        "r Solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откройте для себя мощные возможности NetGenius CRM.
        /// </summary>
        internal static string Discover_the_power_packed_features_of_NetGenius_CRM {
            get {
                return ResourceManager.GetString("Discover the power-packed features of NetGenius CRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узнайте, что говорят наши клиенты!.
        /// </summary>
        internal static string Discover_what_our_customers_have_to_say_ {
            get {
                return ResourceManager.GetString("Discover what our customers have to say!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Погрузитесь в наш блог, чтобы узнать о последних тенденциях, советах и ​​отраслевых знаниях..
        /// </summary>
        internal static string Dive_into_Our_Blog_for_the_Latest_Trends__Tips__and_Industry_Knowledge_ {
            get {
                return ResourceManager.GetString("Dive into Our Blog for the Latest Trends, Tips, and Industry Knowledge.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Докс.
        /// </summary>
        internal static string Docs {
            get {
                return ResourceManager.GetString("Docs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Легкое управление данными: используйте возможности расширенных фильтров в нашей динамической таблице данных. Легко уточняйте и анализируйте информацию, обеспечивая точность и контроль у вас под рукой. Повысьте качество принимаемых на основе данных решений с помощью NetGenius CRM.
        /// </summary>
        internal static string Effortless_Data_Mastery__Harness_the_Power_of_Advanced_Filters_in_our_Dynamic_Data_Table__Seamlessly_refine_and_analyse_information__ensuring_precision_and_control_at_your_fingertips__Elevate_your_data_driven_decisions_with_NetGenius_CRM {
            get {
                return ResourceManager.GetString("Effortless Data Mastery: Harness the Power of Advanced Filters in our Dynamic Dat" +
                        "a Table. Seamlessly refine and analyse information, ensuring precision and contr" +
                        "ol at your fingertips. Elevate your data-driven decisions with NetGenius CRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Легкие финансы, бесперебойные транзакции: использование возможностей нашей усовершенствованной системы выставления счетов.
        /// </summary>
        internal static string Effortless_Finances__Seamless_Transactions__Harnessing_the_Power_of_Our_Advanced_Invoice_System {
            get {
                return ResourceManager.GetString("Effortless Finances, Seamless Transactions: Harnessing the Power of Our Advanced " +
                        "Invoice System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Емайл аутомотитион.
        /// </summary>
        internal static string Email_automation {
            get {
                return ResourceManager.GetString("Email automation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расширьте возможности своей сети с помощью NetGenius CRM.
        /// </summary>
        internal static string Empower_your_network_with_NetGenius_CRM {
            get {
                return ResourceManager.GetString("Empower your network with NetGenius CRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ентерприсе.
        /// </summary>
        internal static string Enterprise {
            get {
                return ResourceManager.GetString("Enterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откройте для себя будущее сетей: повысьте эффективность, максимизируйте производительность и обеспечьте успех с помощью SaaS-решений NetGenius..
        /// </summary>
        internal static string Experience_the_Future_of_Networking__Elevate_Efficiency__Maximize_Performance__and_Secure_Success_with_NetGenius_SaaS_Solutions_ {
            get {
                return ResourceManager.GetString("Experience the Future of Networking: Elevate Efficiency, Maximize Performance, an" +
                        "d Secure Success with NetGenius SaaS Solutions.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посмотри на фековые отзывы.
        /// </summary>
        internal static string Explore_our_customer_proven_success_story {
            get {
                return ResourceManager.GetString("Explore our customer proven success story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изучите все ключевые особенности, которые отличают нашу компанию.
        /// </summary>
        internal static string Explore_the_all_Key_features_that_set_our_company {
            get {
                return ResourceManager.GetString("Explore the all Key features that set our company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оссобенности.
        /// </summary>
        internal static string Feature {
            get {
                return ResourceManager.GetString("Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Футуре план.
        /// </summary>
        internal static string Feature_plan_includes {
            get {
                return ResourceManager.GetString("Feature plan includes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыл пароль.
        /// </summary>
        internal static string Forgot {
            get {
                return ResourceManager.GetString("Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыл пароль.
        /// </summary>
        internal static string Forgot_password {
            get {
                return ResourceManager.GetString("Forgot password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фри платформ аксеес .
        /// </summary>
        internal static string Free_Platform_Access {
            get {
                return ResourceManager.GetString("Free Platform Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трата времени.
        /// </summary>
        internal static string Get_a_production_could_provisioned_with_fully_managed_structure {
            get {
                return ResourceManager.GetString("Get a production could provisioned with fully-managed structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получите бесплатную пробную версию.
        /// </summary>
        internal static string Get_Free_Trial {
            get {
                return ResourceManager.GetString("Get Free Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гет стартед.
        /// </summary>
        internal static string Get_Started {
            get {
                return ResourceManager.GetString("Get Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узнайте напрямую от наших довольных клиентов и партнеров об их опыте работы с нами..
        /// </summary>
        internal static string Hear_Directly_from_Our_Satisfied_Clients_and_Partners_About_Their_Experience_Working_with_Us_ {
            get {
                return ResourceManager.GetString("Hear Directly from Our Satisfied Clients and Partners About Their Experience Work" +
                        "ing with Us.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интеграция.
        /// </summary>
        internal static string Integration {
            get {
                return ResourceManager.GetString("Integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последние новости.
        /// </summary>
        internal static string Latest_News__amp__Articles {
            get {
                return ResourceManager.GetString("Latest News &amp; Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лерн море.
        /// </summary>
        internal static string Learn_More {
            get {
                return ResourceManager.GetString("Learn More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Монтхли.
        /// </summary>
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нам доверяют более 200+ компаний по всему миру.
        /// </summary>
        internal static string More_than_200__companies_trusted_us_worldwide {
            get {
                return ResourceManager.GetString("More than 200+ companies trusted us worldwide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Несколько комбинаций фильтров:.
        /// </summary>
        internal static string Multiple_Filter_Combinations_ {
            get {
                return ResourceManager.GetString("Multiple Filter Combinations:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбор средств NetGenius.
        /// </summary>
        internal static string NetGenius_Fundraise {
            get {
                return ResourceManager.GetString("NetGenius Fundraise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        internal static string NetGenius_price_plan {
            get {
                return ResourceManager.GetString("NetGenius price plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to голы в ворота Реала.
        /// </summary>
        internal static string of_goals_achieved_with_Profit_on_Greenish {
            get {
                return ResourceManager.GetString("of goals achieved with Profit on Greenish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to голы в ворта манчестера.
        /// </summary>
        internal static string of_goals_achieved_with_ROI_on_ProNature {
            get {
                return ResourceManager.GetString("of goals achieved with ROI on ProNature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наш путь, вехи и стремление к совершенству.
        /// </summary>
        internal static string Our_journey__milestones__and_commitment_to_excellence {
            get {
                return ResourceManager.GetString("Our journey, milestones, and commitment to excellence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страницы.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ценовой пакет.
        /// </summary>
        internal static string Price_Package {
            get {
                return ResourceManager.GetString("Price Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квик актион.
        /// </summary>
        internal static string Quick_Action {
            get {
                return ResourceManager.GetString("Quick Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохраненные конфигурации фильтров.
        /// </summary>
        internal static string Saved_Filter_Configurations {
            get {
                return ResourceManager.GetString("Saved Filter Configurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Масштабируйтесь быстрее, чем когда-либо прежде, с NetGenius.
        /// </summary>
        internal static string Scale__faster_then_ever_before_with_NetGenius {
            get {
                return ResourceManager.GetString("Scale  faster then ever before with NetGenius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бесшовное подключение: изучите наши возможности интеграции для повышения эффективности и совместной работы..
        /// </summary>
        internal static string Seamless_Connectivity__Explore_Our_Integration_Capabilities_for_Enhanced_Efficiency_and_Collaboration_ {
            get {
                return ResourceManager.GetString("Seamless Connectivity: Explore Our Integration Capabilities for Enhanced Efficien" +
                        "cy and Collaboration.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регестрация.
        /// </summary>
        internal static string Sing_up {
            get {
                return ResourceManager.GetString("Sing up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Финишер.
        /// </summary>
        internal static string Starter {
            get {
                return ResourceManager.GetString("Starter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешные Истории.
        /// </summary>
        internal static string Success_Stories {
            get {
                return ResourceManager.GetString("Success Stories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поддержка(ее нету).
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индивидуальная ценность, непревзойденный выбор: изучение универсальности нашего ценового пакета.
        /// </summary>
        internal static string Tailored_Value__Unmatched_Choices__Exploring_the_Versatility_of_Our_Price_Package_Feature {
            get {
                return ResourceManager.GetString("Tailored Value, Unmatched Choices: Exploring the Versatility of Our Price Package" +
                        " Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отзывы.
        /// </summary>
        internal static string Testimonial {
            get {
                return ResourceManager.GetString("Testimonial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общий сбор средств.
        /// </summary>
        internal static string Total_Fundraise {
            get {
                return ResourceManager.GetString("Total Fundraise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего пользователей.
        /// </summary>
        internal static string Total_Users {
            get {
                return ResourceManager.GetString("Total Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Надежный рост, доказанный успех: изучение эволюции, достижений и видения нашей компании на будущее..
        /// </summary>
        internal static string Trusted_Growth__Proven_Success__Exploring_Our_Company__x27_s_Evolution__Achievements__and_Vision_for_the_Future_ {
            get {
                return ResourceManager.GetString("Trusted Growth, Proven Success: Exploring Our Company&#x27;s Evolution, Achieveme" +
                        "nts, and Vision for the Future.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анлимитед дата.
        /// </summary>
        internal static string Unlimited_data {
            get {
                return ResourceManager.GetString("Unlimited data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посмотреть на фейковые истории.
        /// </summary>
        internal static string View_Success_Story {
            get {
                return ResourceManager.GetString("View Success Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вивс.
        /// </summary>
        internal static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ерли.
        /// </summary>
        internal static string Yearly {
            get {
                return ResourceManager.GetString("Yearly", resourceCulture);
            }
        }
    }
}
