//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetGenius.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetGenius.Resources.Views.Home.Index.en", typeof(Index_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Smarter, Faster, and More Secure Network Experience.
        /// </summary>
        internal static string A_Smarter__Faster__and_More_Secure_Network_Experience {
            get {
                return ResourceManager.GetString("A Smarter, Faster, and More Secure Network Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Filtering.
        /// </summary>
        internal static string Advanced_Filtering {
            get {
                return ResourceManager.GetString("Advanced Filtering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        internal static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        internal static string Coming_Soon {
            get {
                return ResourceManager.GetString("Coming Soon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email.
        /// </summary>
        internal static string Confirm_email {
            get {
                return ResourceManager.GetString("Confirm email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM Power Feature.
        /// </summary>
        internal static string CRM_Power_Feature {
            get {
                return ResourceManager.GetString("CRM Power Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data table - (Advance filter).
        /// </summary>
        internal static string Data_table____Advance_filter_ {
            get {
                return ResourceManager.GetString("Data table - (Advance filter)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the power-packed features of NetGenius CRM.
        /// </summary>
        internal static string Discover_the_power_packed_features_of_NetGenius_CRM {
            get {
                return ResourceManager.GetString("Discover the power-packed features of NetGenius CRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effortless Data Mastery: Harness the Power of Advanced Filters in our Dynamic Data Table. Seamlessly refine and analyse information, ensuring precision and control at your fingertips. Elevate your data-driven decisions with NetGenius CRM.
        /// </summary>
        internal static string Effortless_Data_Mastery__Harness_the_Power_of_Advanced_Filters_in_our_Dynamic_Data_Table__Seamlessly_refine_and_analyse_information__ensuring_precision_and_control_at_your_fingertips__Elevate_your_data_driven_decisions_with_NetGenius_CRM {
            get {
                return ResourceManager.GetString("Effortless Data Mastery: Harness the Power of Advanced Filters in our Dynamic Dat" +
                        "a Table. Seamlessly refine and analyse information, ensuring precision and contr" +
                        "ol at your fingertips. Elevate your data-driven decisions with NetGenius CRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empower your network with NetGenius CRM.
        /// </summary>
        internal static string Empower_your_network_with_NetGenius_CRM {
            get {
                return ResourceManager.GetString("Empower your network with NetGenius CRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience the Future of Networking: Elevate Efficiency, Maximize Performance, and Secure Success with NetGenius SaaS Solutions..
        /// </summary>
        internal static string Experience_the_Future_of_Networking__Elevate_Efficiency__Maximize_Performance__and_Secure_Success_with_NetGenius_SaaS_Solutions_ {
            get {
                return ResourceManager.GetString("Experience the Future of Networking: Elevate Efficiency, Maximize Performance, an" +
                        "d Secure Success with NetGenius SaaS Solutions.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature.
        /// </summary>
        internal static string Feature {
            get {
                return ResourceManager.GetString("Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot.
        /// </summary>
        internal static string Forgot {
            get {
                return ResourceManager.GetString("Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Free Trial.
        /// </summary>
        internal static string Get_Free_Trial {
            get {
                return ResourceManager.GetString("Get Free Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 200+ companies trusted us worldwide.
        /// </summary>
        internal static string More_than_200__companies_trusted_us_worldwide {
            get {
                return ResourceManager.GetString("More than 200+ companies trusted us worldwide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Filter Combinations:.
        /// </summary>
        internal static string Multiple_Filter_Combinations_ {
            get {
                return ResourceManager.GetString("Multiple Filter Combinations:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetGenius Fundraise.
        /// </summary>
        internal static string NetGenius_Fundraise {
            get {
                return ResourceManager.GetString("NetGenius Fundraise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Filter Configurations.
        /// </summary>
        internal static string Saved_Filter_Configurations {
            get {
                return ResourceManager.GetString("Saved Filter Configurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string Sign_up {
            get {
                return ResourceManager.GetString("Sign up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Stories.
        /// </summary>
        internal static string Success_Stories {
            get {
                return ResourceManager.GetString("Success Stories", resourceCulture);
            }
        }
    }
}
